# Generated by Django 5.0.4 on 2024-04-26 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearchdata',
            name='device_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
