# Generated by Django 5.0.4 on 2024-04-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0002_mysearchdata_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysearchdata',
            name='device_token',
        ),
    ]
