# Generated by Django 5.0.4 on 2024-04-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0003_remove_mysearchdata_device_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysearchdata',
            old_name='create_at',
            new_name='time',
        ),
    ]
