# Generated by Django 5.0.4 on 2024-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0004_rename_create_at_mysearchdata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFoodBankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('coporation', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
