# Generated by Django 5.0.4 on 2024-04-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0005_myfoodbankmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('x', models.CharField(max_length=100, verbose_name='x')),
                ('y', models.CharField(max_length=100, verbose_name='y')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
            ],
        ),
    ]
