# Generated by Django 5.0.4 on 2024-05-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0008_foodrecipy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipy',
            name='clss',
            field=models.CharField(max_length=300, verbose_name='clss'),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='cookdsrt',
            field=models.CharField(max_length=300, verbose_name='fooddscrt'),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='cookmth',
            field=models.CharField(max_length=300, verbose_name='foodnm'),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='fooddscrt',
            field=models.CharField(max_length=300, verbose_name='fooddscrt'),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='foodmntr',
            field=models.CharField(max_length=300, verbose_name='clss'),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='foodnm',
            field=models.CharField(max_length=300, verbose_name='foodnm'),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='ingt',
            field=models.CharField(max_length=300, verbose_name='ingt'),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='url',
            field=models.CharField(max_length=300, verbose_name='clss'),
        ),
    ]
