# Generated by Django 5.0.4 on 2024-05-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0009_alter_foodrecipy_clss_alter_foodrecipy_cookdsrt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipy',
            name='clss',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='cookdsrt',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='cookmth',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='fooddscrt',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='foodmntr',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='foodnm',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='ingt',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
