# Generated by Django 5.0.4 on 2024-05-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0010_alter_foodrecipy_clss_alter_foodrecipy_cookdsrt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrecipy',
            old_name='fooddscrt',
            new_name='foodscrt',
        ),
    ]
