# Generated by Django 5.0.4 on 2024-05-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0011_rename_fooddscrt_foodrecipy_foodscrt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipy',
            name='clss',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='cookdsrt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='cookmth',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='foodmntr',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='foodnm',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='foodscrt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='ingt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodrecipy',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
