# Generated by Django 5.0.4 on 2024-05-11 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSearch', '0013_crawleddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='img',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
